### ISSUE TITLE
[export] Bug when clicking "Export" button while lucene query field is focused

### ISSUE THREAD

**Issue by colllin** [auth0-extensions/auth0-user-import-export-extension#10]
The clicking of the button blurs the lucene query field, which triggers the query to re-run, which confuses the export tool which now displays "exporting undefined users" (where undefined should be the user count).

![image](https://cloud.githubusercontent.com/assets/185923/22084095/edd73662-dd8b-11e6-9a69-9e3d66bd52ba.png)

**Comment by ademartini** [comment]
Thank you Collin for the feedback.  We have added this bug to our backlog.
