### ISSUE TITLE
[export] UX issues

### ISSUE THREAD

**Issue by colllin** [auth0-extensions/auth0-user-import-export-extension#11]
While I'm here...

The lucene search feature wasn't very intuitive.  It wasn't clear whether the search was triggered automatically, or when I did manage to trigger it, it wasn't clear exactly what triggered it.  My best guess as a web developer is that it is searching on 'change' or 'blur', but if that's the case, there *should* be a button to trigger it, since naturally you would want to hit enter or click something to tell it to "go", if auto-search is too expensive.  It's unnatural to click away from the thing you're trying to use in order to get it to do something.   In fact, my coworker is asking me for instructions on how to use this UI, even though I'm pretty sure he's used it before, and he's a developer, so he should be able to figure it out without instructions... I think?

**Comment by ademartini** [comment]
Thank you for the input Collin, we have moved these suggestions to our backlog.
