### ISSUE TITLE
Support CSV imports

### ISSUE THREAD

**Issue by sandrinodimattia** [auth0-extensions/auth0-user-import-export-extension#12]
Allow users to upload CSV files instead of JSON files. The structure should be as follows:

```
email,username,app_metadata.age
john@example.com,john,20
```

The header should contain the exact names of the fields. After uploading the CSV, we can then convert the file to a JSON file and upload it to API v2

**Comment by mschmoyer** [comment]
This would be great. We would love to have imports handled by a team who works with CSV files regularly, but does not have the expertise to convert/manage a JSON file.

**Comment by ademartini** [comment]
Thanks Sandrino, we have moved this to our internal backlog.
