### ISSUE TITLE
When users are imported we need to see the reason of the failed imports.

### ISSUE THREAD

**Issue by saltukalakus** [auth0-extensions/auth0-user-import-export-extension#13]
Can we display the reason why some users are not imported in the extension UI.

**Comment by saltukalakus** [comment]
I guess, we need to show the result from this endpoint => https://auth0.com/docs/api/management/v2#!/Jobs/get_errors

**Comment by ademartini** [comment]
Hi Saltuk, thank you. This has been moved to our internal backlog.
