### ISSUE TITLE
Export Errors are not presented on the UX

### ISSUE THREAD

**Issue by mostekcm** [auth0-extensions/auth0-user-import-export-extension#17]
A customer was trying to add a sort field but they added user.user_id instead of just user_id.  The API responded with a nice error message, but it was hidden in the developer tools.  It would be nice if that error were presented on the UX instead.  This also would let users know that there was an error and not just a stalled export.

**Comment by ademartini** [comment]
Hey Carlos, this is currently as-designed.  We want to support any arbitrary field, that may or may not exist on every user.
