### ISSUE TITLE
Page freezes when trying to upload two files with the same name

### ISSUE THREAD

**Issue by rolodato** [auth0-extensions/auth0-user-import-export-extension#2]
Steps to reproduce (only tested on Firefox):
1. Upload file `a.json`, suppose it fails
2. Make a change to file `a.json` trying to correct the error, preserving the filename
3. Try to upload the updated file

The "Import Status" column goes blank, and trying to remove any of the entries causes the page to freeze:

![screen shot 2016-05-02 at 16 23 48](https://cloud.githubusercontent.com/assets/829698/14965178/4690a91e-1082-11e6-891d-70e0209922ae.png)

**Comment by ademartini** [comment]
We were unable to reproduce this issue.  Please feel free to reach out to Auth0 support with any further questions.
