### ISSUE TITLE
Composed field

### ISSUE THREAD

**Issue by mirkods** [auth0-extensions/auth0-user-import-export-extension#27]
Hi,
I need in my export a composed field derived from the concatenation of 2 field like for example:
```Javascript
// user model
{
...
    "user_metadata": {
        "first_name": "First name",
        "last_name": "Last name",
    }
}
```

I'd like to have in my csv a field `full_name` calculated chaining `first_name` and `last_name`.

Is there some way to do this with the current version?

Cheers,
Mirko

**Comment by ademartini** [comment]
Thank you Mirko, we have added this to our internal backlog.
