### ISSUE TITLE
Support for `upsert`

### ISSUE THREAD

**Issue by fyockm** [auth0-extensions/auth0-user-import-export-extension#32]
[/api/v2/jobs/users-imports](https://auth0.com/docs/api/management/v2#!/Jobs/post_users_imports) supports `upsert` to "Update the user if already exists". The extension should provide an affordance for the same functionality.

**Comment by andreasvirkus** [comment]
The extension actually says that the import of some users failed with the following error:
```
Unable to import user "andreas@qualitista.com":
            	The user already exist and upsert parameter is false
```

So it's sort of controversial that the extension itself doesn't provide a way to pass in the `upsert` param.

**Comment by braime** [comment]
Controversial indeed... I am also missing the `upsert` parameter in the import settings a lot. Do other users really delete their DB and the rebuild it completely from JSON? Another (semi-related) question, is there technically any workaround to upsert the user_id of a user (with the import/export extension) or is this just not possible by design? Thanks!

**Comment by kazdegroot** [comment]
Any progress on this issue?

**Comment by leog** [comment]
Bumped into this too, please consider adding `upsert` as a parameter.

**Comment by ademartini** [comment]
Thank you for the great suggestion.  We have moved this to our internal backlog.

**Comment by jinendramehta-kevit** [comment]
I am also facing in passing boolean fields like upsert and send_completion_email.

**Comment by ramonleon-ms** [comment]
any updates on this?

**Comment by gregfenton** [comment]
nudge.

**Comment by jonschmidt** [comment]
Not having this is really unfortunate, and is forcing us to wait til the last possible second to migrate our users adding more risk. This seems incredibly easy to implement. It's just passing through a boolean flag isn't it?

**Comment by henrymcl** [comment]
nudging this after 2 years.
