### ISSUE TITLE
JSON export is not valid json

### ISSUE THREAD

**Issue by ed-sparkes** [auth0-extensions/auth0-user-import-export-extension#45]
The json exported when selecting json format is not valid json as there is no enclosing array and items are not comma separated. This makes it a pain for onward processing out of system as have to go in and add the commas and enclosing braces in a text editor

```
{"Id":"sdgfdsg"}
{"Id":"sdgfdsg"}
```
should be 
```
[
  {"Id":"sdgfdsg"},
  {"Id":"sdgfdsg"}
]
```

**Comment by btoro** [comment]
I'm still seeing this issue...

**Comment by ed-sparkes** [comment]
Hmm im closing this as it seems it is intentional. 

https://auth0.com/docs/users/guides/bulk-user-exports

```
Auth0's export files use the ndjson format due to the large size of the export files, while the import functionality expects a JSON file.

Before you can import users using an export generated by Auth0, you'll need to convert the file from ndjson to json using the library of your choice (such as jq).
```
