### ISSUE TITLE
Accessing user.user_metadata[something] returning undefined

### ISSUE THREAD

**Issue by toadkicker** [auth0-extensions/auth0-user-import-export-extension#7]
Hello!

Thanks for this tool, it is incredibly useful. I'm exporting and trying to access user.user_metadata.whatever and getting an undefined back. However I know that user.user_metadata is present because it outputs [Object object]. Why is this different from app_metadata? How do I get to user_metadata?

**Comment by sandrinodimattia** [comment]
That's strange, I just tested with `user.user_metadata && user.user_metadata.color` and this works fine.

Could you try the following?

```
user.user_metadata && user.user_metadata["fieldName"]
```

**Comment by ademartini** [comment]
Since we haven't heard any activity on this issue in a while, we are going to close it.  Feel free to reach out to Auth0 support with any further inquiry.
